server:
  port: 9223

spring:
  application:
    name: redis-list

  redis:
    database: 0
    host: localhost
    port: 6379
    #password:
    timeout: 1000

    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        max-wait: 1000
        min-idle: 0
        time-between-eviction-runs: 1000
